# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Vehicle Selector Pro"
client_id = "1ace4dd6082915935f0901c26f37d4a0"
application_url = "https://vehicle-selector-pro.fly.dev"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_product_listings,read_customers,write_customers"
use_legacy_install_flow = false
optional_scopes = [ ]

[auth]
redirect_urls = [ "https://vehicle-selector-pro.fly.dev/auth/shopify/callback" ]

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/products_create"
  topics = [ "products/create" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/products_update"
  topics = [ "products/update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/products_delete"
  topics = [ "products/delete" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app_uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop_update"
  topics = [ "shop/update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers_data_request"
  topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers_redact"
  topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop_redact"
  topics = [ "shop/redact" ]

[app_proxy]
url = "https://vehicle-selector-pro.fly.dev/apps/vehicle-selector"
subpath = "vehicle-selector"
prefix = "apps"

[pos]
embedded = true
